FROM python:3.9-slim-buster
 
WORKDIR /code
 
COPY ./requirements.txt /code/requirements.txt

RUN apt-get update && \
    apt-get -y install libgl1-mesa-glx && \
    apt-get -y install libglib2.0-0
 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
 
COPY ./app /code/app
 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
